# Generated by Django 2.0.5 on 2018-05-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='facv_id',
            new_name='fav_id',
        ),
    ]
