# Generated by Django 2.0.5 on 2018-05-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180517_2310'),
        ('courses', '0002_auto_20180516_1116'),
    ]

    operations = [

    ]
