# Generated by Django 2.0.5 on 2018-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程类别'),
        ),
    ]
